alias huc='heroku create fastchart --buildpack heroku/python'
alias hud='heroku destroy'
alias hug='heroku logs -tail'
alias hul='heroku login'
alias hur='heroku git:remote -a fastchart'
alias gpu='git subtree push --prefix fastchart heroku master'