# generated by fastapi-codegen:
#   filename:  fxgit-FastChart-1.0.0-resolved.yaml
#   timestamp: 2020-12-06T04:26:57+00:00

from __future__ import annotations

from typing import Optional

from fastapi import FastAPI

from .models import (
    InpDateend,
    InpDatelen,
    InpDaterel,
    InpDatestart,
    InpSub,
    InpSubperiod,
    InpSymbol,
    InpTa,
    InpTaPeriod,
    RetChart,
)

app = FastAPI(
    title="FastChart API",
    description="stock chart as a service",
    contact="{'name': 'dennislwm', 'url': 'https://github.com/dennislwm'}",
    version="1.0.0",
)


@app.get('/symbol/{id}', response_model=RetChart)
def get_symbol_id(
    id: InpSymbol,
    daterel: Optional[InpDaterel] = None,
    datelen: Optional[InpDatelen] = None,
    datestart: Optional[InpDatestart] = None,
    dateend: Optional[InpDateend] = None,
    ta: Optional[InpTa] = None,
    period: Optional[InpTaPeriod] = None,
) -> RetChart:
    pass


@app.get('/symbol/{id}/sub/{sub}', response_model=RetChart)
def get_symbol_id_sub_sub(
    id: InpSymbol,
    sub: InpSub,
    subperiod: Optional[InpSubperiod] = None,
    daterel: Optional[InpDaterel] = None,
    datelen: Optional[InpDatelen] = None,
    datestart: Optional[InpDatestart] = None,
    dateend: Optional[InpDateend] = None,
    ta: Optional[InpTa] = None,
    period: Optional[InpTaPeriod] = None,
) -> RetChart:
    pass
