# generated by datamodel-codegen:
#   filename:  fxgit-FastChart-1.0.0-resolved.yaml
#   timestamp: 2020-12-06T04:26:57+00:00

from __future__ import annotations

from datetime import date
from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field, conint


class InpSymbol(BaseModel):
    __root__: str = Field(..., description='Symbol', example='SPY')


class InpTa(Enum):
    SMA = 'SMA'
    EMA = 'EMA'


class InpTaPeriod(BaseModel):
    __root__: conint(ge=2) = Field(..., description='Ta Period')


class InpSub(Enum):
    RSI = 'RSI'


class InpSubperiod(BaseModel):
    __root__: conint(ge=2) = Field(..., description='Sub Period')


class InpDaterel(Enum):
    YTM = 'YTM'
    M = 'M'
    YTQ = 'YTQ'
    Q = 'Q'
    YTD = 'YTD'
    Y = 'Y'


class InpDatelen(BaseModel):
    __root__: int = Field(..., description='Relative date length')


class InpDatestart(BaseModel):
    __root__: date = Field(
        ..., description='The start date. Must be used with end date.'
    )


class InpDateend(BaseModel):
    __root__: date = Field(
        ..., description='The end date. Must be used with start date.'
    )


class RetChart(BaseModel):
    id: Optional[str] = Field(None, example='SPY')
    url: Optional[str] = Field(None, example='https://fastchart.myvnc.com/img/SPY.png')
