# generated by datamodel-codegen:
#   filename:  api_open/fxgit-FastChart-0.2.0-resolved.yaml
#   timestamp: 2021-01-20T03:10:35+00:00

from __future__ import annotations

from pydantic import BaseModel


class SchError(BaseModel):
    code: str
    message: str
