# generated by fastapi-codegen:
#   filename:  fxgit-FastChart-0.2.0-resolved.yaml
#   timestamp: 2021-01-20T03:10:35+00:00

from __future__ import annotations

from typing import Optional

from fastapi import FastAPI

# Insert import code
from .lib.fastchart import FastChart

app = FastAPI(
    title='FastChart API',
    description='stock chart as a service',
    contact={'name': 'dennislwm', 'url': 'https://github.com/dennislwm'},
    version='0.2.0',
)

# Insert instance code
objFastchart = FastChart()

@app.get("/")
async def read_root():
    return {
        "name": "fastchart",
        "version": f"Hello world! From FastAPI running on Uvicorn."
    }

@app.get('/{symbol}', response_model=None)
async def get_symbol(
    symbol: str, main: Optional[str] = None, sub: Optional[str] = None
) -> None:
    """
    Fastchart is an alternative to TradingView
    """
    # Insert method
    objFastchart.get_symbol(symbol, main, sub)
